name: Publish to GitHub Packages

on:
  push:
    branches:
      - master  # or the branch you want to trigger this action on
  workflow_dispatch:  # Only trigger if this file changes (you can add other paths too)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Set your required Java version

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Packages
      run: ./gradlew publish --no-daemon
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
