name: Publish New Tag

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  create-tag:
    name: Create and Push Date-Based Tag
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Git User
      - name: Setup Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Get Latest Date-Based Tag
      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-creatordate | grep -E '^[0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}$' | head -n 1 || echo "2025.1.0")
          echo "Latest tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      # Step 4: Calculate Next Date-Based Tag
      - name: Calculate Next Tag
        id: calculate_next_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          year=$(echo $latest_tag | cut -d. -f1)
          month=$(echo $latest_tag | cut -d. -f2)
          day=$(echo $latest_tag | cut -d. -f3)

          # Increment the day
          day=$((day + 1))

          # Handle overflow for months (if desired, add more date logic as needed)
          if [ "$day" -gt 31 ]; then
            day=1
            month=$((month + 1))
          fi

          if [ "$month" -gt 12 ]; then
            month=1
            year=$((year + 1))
          fi

          # Format the new tag as YYYY.MM.DD
          new_tag=$(printf "%d.%d.%d" $year $month $day)
          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      # Step 5: Create and Push the New Tag
      - name: Create and Push Tag
        run: |
          new_tag=${{ steps.calculate_next_tag.outputs.new_tag }}
          git tag $new_tag
          git push origin $new_tag
